version: '3'
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /src
    command: /src/scripts/docker.sh
    environment:
      - DATASTORE_PATH=/datastore/datastore.db
    volumes:
      - .:/src
      - ./.datastore:/datastore
    ports:
      - "8000:8000"
      - "8080:8080"
      - "8081:8081"
